services:
  db:
    container_name: data_dump_db
    image: mongo
    volumes:
      - ./db:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_KEY}
    network_mode: bridge
  api:
    container_name: data_dump_api
    build:
      context: ./api
    depends_on:
      - db
    links:
     - db:db
    restart: always
    environment:
      AGENT_KEY: ${AGENT_KEY}
      DB_KEY: ${DB_ROOT_KEY}
      VIRTUAL_HOST: dump.techiteasy.ca
      LETSENCRYPT_HOST: dump.techiteasy.ca
      LETSENCRYPT_EMAIL: sysadmin@techiteasy.ca
    volumes:
      - ./api:/api
    working_dir: /api
    entrypoint: gunicorn entrypoint:app -w 1 --threads 1 -b 0.0.0.0:80
    # uncomment to test locally with http://localhost:
    # ports:
    #   - 80:80
    network_mode: bridge
  admin:
    container_name: data_dump_admin
    build:
      context: ./mongo-express
    depends_on:
      - db
    links:
     - db:db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_KEY}
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_KEY}
      VCAP_APP_PORT: 8081
      VIRTUAL_HOST: dump-admin.techiteasy.ca
      LETSENCRYPT_HOST: dump-admin.techiteasy.ca
    network_mode: bridge
    # uncomment to test locally with http://localhost:8081:
    # ports:
    #   - 1337:8081